services:
  db:
    image: mysql:9.4.0
    container_name: voyatek_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATABASE_PASSWORD}"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 30s

  redis:
    image: redis:8.2.1-alpine
    container_name: voyatek_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 3s
      retries: 5
      interval: 5s
      start_period: 10s

  app:
    build: .
    container_name: voyatek_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PORT: 3000
      EXTERNAL_PORT: 4000
      # Prisma DATABASE_URL used by Prisma Client inside the app, built from user's .env vars
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
      # Map our existing env.ts expectations to container hosts
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "4000:3000"
    restart: unless-stopped
    command: sh -c "sleep 5 && npx prisma migrate deploy && node dist/index.js"

volumes:
  db_data:
  redis_data:
